# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.DecimalField(decimal_places=0, max_digits=100)),
                ('desciption', models.CharField(blank=True, max_length=100)),
                ('is_handsome', models.BooleanField()),
            ],
        ),
    ]
